- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "me@jfroffice.me"
  tags:
  - git-personal
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "jfroffice"
  tags:
  - git-personal
